### PR TITLE
update for react native 0.40

### PR DESCRIPTION
**Pull request by mikestek**

### CODE REVIEW

**Comment by joncursi** [comment]
👍

**Comment by joncursi** [comment]
For anyone else who is waiting on this, and unable to upgrade to RN 0.40.0 as a result, I created a temporary, forked version of this repo here: https://github.com/joncursi/react-native-material-kit

Add it to package.json with:

```
    "react-native-material-kit": "git+ssh://git@github.com/joncursi/react-native-material-kit.git",
```

I will delete the fork once this is merged.

**Comment by iRoachie** [comment]
Thanks for merge!

**Comment by iRoachie** [comment]
@Crash-- Could you comment here when you pushed new version to npm? Thanks

**Pull request merged**
