### PR TITLE
[Issue #174] <TextField /> is not remeasured on orientation change

### LINKED ISSUE #174: MKTextField does not change width upon orientation change
hello! thanks for this awesome lib.
I noticed that when changing screen orientation, the width of MKTextField stays the same.

How to reproduce:
1create MKTextField
2 run app in portrait mode
3 switch to landscape - MKTextField will keep its width

### PR DESCRIPTION
**Pull request by jurassix**
Resolve #174 `<TextField />` is not being updated then orientation changes.

### CODE REVIEW

**Comment by jurassix** [comment]
@xinthink - any feedback on this PR? I can provide screenshots of before vs after if you would like?

**Comment by xinthink** [comment]
hi @jurassix thanks for the PR. I'll check it out later.

**Comment by jurassix** [comment]
@xinthink anything you need from me to help get this merged in? Just let me know, Thanks!

**Comment by Crash--** [comment]
Thank you for your contribution @jurassix !

**Pull request merged**
