### PR TITLE
Improve floating label animations

### PR DESCRIPTION
**Pull request by lynndylanhurley**
Adds scale + color transitions to the floating label animation. See the attached image:

floating-text-animation

Tested on both iOS and Android.

### CODE REVIEW

**Comment by lynndylanhurley** [comment]
54dcf54 fixes the slight jank in the animation above.

**Comment by lynndylanhurley** [comment]
Here is a demo of the latest improvements:
floating-labels-2

**Comment by lynndylanhurley** [comment]
@xinthink - comments?

**Comment by xinthink** [comment]
Sorry for replying late, and thanks for the PR.
I'll look into it later.

**Comment by lynndylanhurley** [comment]
Thanks @xinthink!

**Comment by anhldbk** [comment]
@lynndylanhurley Thanks for such elegant effect.

**Comment by lynndylanhurley** [comment]
:smiley:

**Comment by xinthink** [comment]
@lynndylanhurley Thanks for the great work :beers:

**Comment by lynndylanhurley** [comment]
Thank you for the great library :)

**Pull request merged**
