### PR TITLE
Fixes react 0.60 issue with deprecated sendInutEventWithName:

### PR DESCRIPTION
**Pull request by ls-kelsey-regan**

### CODE REVIEW

**Comment by Crash--** [comment]
Thank you for the fix :)

**Comment by kregan-lightspeed** [comment]
Great fix!

**Comment by muratakbal** [comment]
thx for the fix.

@Crash-- are you planning release a version that includes this fix on `npm` soon?

**Comment by MLY123** [comment]
Xcode 10.3 
RN 0.60.5 
还是会报错

**Pull request merged**
