### PR TITLE
Add error field to FloatingTextField

### PR DESCRIPTION
**Pull request by NishanthShankar**
Signed-off-by: Nishanth Shankar <nishanthShankr@gmail.com>

### CODE REVIEW

**Comment by Crash--** [comment]
Hi @NishanthShankar, why did you close the PR? Seems to be an useful feature

**Comment by NishanthShankar** [comment]
It was kind of incomplete.. Will make another proper PR for it soon

**Comment by Crash--** [comment]
Nice! 👍

**Comment by fchennouf** [comment]
Hi @NishanthShankar any update about the PR ?

**Pull request closed without merging**
