### PR TITLE
support RN0.33.0

### PR DESCRIPTION
**Pull request by paulbao**

### CODE REVIEW

**Comment by bakyeono** [comment]
screenshot_20160914_184404

Patch no works.

**Comment by paulbao** [comment]
Looks like you've missed this [commit](https://github.com/xinthink/react-native-material-kit/pull/232/commits/02efea61dbaf6146b7e20c39c5240142b271caba)

**Comment by mschipperheyn** [comment]
Seems to do the trick! Thanks!

**Comment by Crash--** [comment]
Thank you @paulbao for this fix!

**Comment by mmoutenot** [comment]
Worked for me on react-native 0.33. Thanks!

**Pull request merged**
