### PR TITLE
added snapping to step (with default step = 1)

### PR DESCRIPTION
**Pull request by israelidanny**
This is an adaptation of the existing feature in `RangeSlider` for `Slider`

### CODE REVIEW

**Comment by Crash--** [comment]
Thank @israelidanny for this PR. 

I'm wondering what is your use case for it? You needed a Slider for more than 2 values?

**Comment by israelidanny** [comment]
This is an adaptation of `snap` :) 
I needed a slider of 1-5 values that snaps with a step of 1 (1.5, 2.5 or 3.356 weren't acceptable values)

**Comment by israelidanny** [comment]
So, is there any reason this can't be merged? :) There's already a similar feature on `RangeSlider`.

**Comment by Crash--** [comment]
I didn't have the time to test it yet. That's why... Can you add some documentation to the readme ?

**Comment by israelidanny** [comment]
What kind of documentation do you think can be helpful? 

I checked if there's anything for this exact feature in `RangeSlider` and it's only documented in the annotated source (I also documented there).

**Comment by urbanvikingr** [comment]
Hi,
Is there anyway, that we (me and @israelidanny) can help with getting this approved and merged?

We would like to contribute. Just let us know.

We would get this accepted, so we don't use a forked version for our project.

**Comment by Crash--** [comment]
I'll take a look today

**Comment by Crash--** [comment]
Can you give me a code example? Like that I'll be able to update the demo project, test it and merge it ;)

**Comment by Crash--** [comment]
Just tested it, works like a charm. 

Thank you for the PR!

**Pull request merged**
