### PR TITLE
- Fixed IOS / Android issue with the spinner, was returning an error …

### PR DESCRIPTION
**Pull request by mikehuebner**
…due to no Spinner component. (only spinner.ios.js and spinner.android.js)

### CODE REVIEW

**Comment by xinthink** [comment]
Hi @mikehuebner, what's problem are you trying to fix? Why there should be a SpinnerIOS and a SpinnerAndroid? I don't think it's a good idea.

**Comment by mikehuebner** [comment]
There was 2 different files in the source and I was getting errors in the console, and this is what fixed it for me. There is a spinner.ios and spinner.android, no spinner.js. So I was just suggesting a fix 😅 you can deny it but this was my fix. I don't think it's a great idea either, but you know 😅

**Comment by xinthink** [comment]
Sorry, I'm closing this.
And thank you anyway, feel free to shoot me another PR if you can find a better solution.

**Comment by mikehuebner** [comment]
I figured out why I did this PR in the first place.

With a webpack setup, the server doesn't know to parse .ios and .android as regular files.
So `import Spinner from './Spinner';` returns a failed error because technically, `Spinner.js` doesn't exist in Webpacks mind. My work around for this just made it work. And sadly, that isn't the solution for it. I just started to realize that was the issue at hand.

On the other hand, this PR can stay closed because it is not a problem with this library, its a webpack issue I'm trying to fix right now. I might create a plugin for it. Thanks though!

**Pull request closed without merging**
