### PR TITLE
[Issue 269] Index prop necessary for dynamic input textfield.

### PR DESCRIPTION
**Pull request by Freydal**
Adding a static fix for the issue.  Could update with a dynamic solution if preferred.

### CODE REVIEW

**Comment by Crash--** [comment]
Just read the issue #269. I think a dynamic solution can be better. At least everyone will be able to add props they want. Something like `...additionalInputProps` is great :)

**Comment by Freydal** [comment]
Sounds great.  I wasn't sure how the more advanced change would go over since I didn't get much feedback with the issue.  I'll take care of this later today.

**Comment by Freydal** [comment]
Alright, let me know what you think.   I can update the readme if you feel its appropriate.

**Comment by Crash--** [comment]
Yep, can you update the Readme also please? Thank you

**Comment by Freydal** [comment]
Sorry for the delays but the Holidays had me a little distracted.   I didn't see much relevance on the readme page aside for the link to xinthink.  I believe my changes will reflect the updated information appropriately.

**Comment by Crash--** [comment]
thank you for the PR

**Pull request merged**
